version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voter-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  cache-init:
    image: redis/redis-stack:latest
    volumes:
      - ./cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend
    command: /data/load-redis.sh cache
    depends_on:
      cache:
        condition: service_started
    
    
  voter-api:
    # build:
    #   context: ./api
    #   dockerfile: dockerfile
    image: ninjaversionfive0/voter-api:latest
    container_name: voter-api-1
    restart: always
    ports:
      - '1080:1080'
    environment:
      - REDIS_URL=cache:6379
    depends_on:
      cache-init:
        condition: service_completed_successfully
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true
